L=https://titan.gml-team.ru:5003/fsdownload/icbdlyZzM/musiq_koniq_ckpt-e95806b9.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/EgvfOC4Gi/DBCNN_KonIQ10k-254e8241.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/ftzaIPN7m/brisque_svm_weights.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/L1BMGj7WU/PieAPPv0.1-0937b014.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/0c4EI4weM/ILNIQE_templateModel.mat
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/nzyW5gnIk/niqe_modelparameters.mat
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/tuWrAcAQm/DISTS_weights-f5e65c96.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/VbMMUlwlB/LPIPS_v0.1_alex-df73285e.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"
L=https://titan.gml-team.ru:5003/fsdownload/jbQsgqDZg/LPIPS_v0.1_vgg-a78928a0.pth
wget --backups=1 -nv "$L" "$L"; rm "$(basename "$L").1"